# Base config file which stores the default parameters which apply to all model configurations
---

# Root directory of your project; type "pwd" in the command line to find it
root_dir: "C:/Users/bsele/Documents/Programming/machine-learning/detectors"

input_data: "data/input.txt"

# Local path for output_files
output_path: "output"

# Parameters for the dataset class
data:

  # Path to the root of the dataset
  root: "/mnt/c/Users/bsele/Documents/Datasets/capella-sar"

  # Path to the sicd chips
  chips: "/home/bselee/programming/sar-toolkit/output/sicd_chips/CAPELLA_C02_SM_SICD_HH_20210215180158_20210215180202"

# Parameters for the defocus script
defocus:
  # File type to defocus; either sicd or chip
  image_type: "sicd"

  # Order of polynomial phase error
  phase_err_order: 5

  # Random seed for polynomial coefficients; use null for no seed
  seed: 42