# Base config file which stores the default parameters which apply to all model configurations
---

# Root directory of your project; type "pwd" in the command line to find it
root_dir: "C:/Users/bsele/Documents/Programming/machine-learning/detectors"

input_data: "data/input.txt"

output_path: "output"

# Parameters for the dataset class
data:

  # Path to the root of the dataset
  root: "/mnt/c/Users/bsele/Documents/Datasets/capella-sar"

  # Path to the sicd chips
  chips: "/home/bselee/programming/sar-toolkit/output/sicd_chips/CAPELLA_C02_SM_SICD_HH_20210215180158_20210215180202"